{
  "schema_version": "1.4.0",
  "id": "GHSA-6749-m5cp-6cg7",
  "modified": "2024-02-24T00:30:20Z",
  "published": "2024-02-24T00:30:20Z",
  "aliases": [
    "CVE-2024-27132"
  ],
  "details": "Insufficient sanitization in MLflow leads to XSS when running an untrusted recipe.\n\nThis issue leads to a client-side RCE when running an untrusted recipe in Jupyter Notebook.\n\nThe vulnerability stems from lack of sanitization over template variables.\n\n",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H"
    }
  ],
  "affected": [

  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-27132"
    },
    {
      "type": "WEB",
      "url": "https://github.com/mlflow/mlflow/pull/10873"
    },
    {
      "type": "WEB",
      "url": "https://research.jfrog.com/vulnerabilities/mlflow-untrusted-recipe-xss-jfsa-2024-000631930"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-79"
    ],
    "severity": "HIGH",
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2024-02-23T22:15:55Z"
  }
}